//
//  BookListRouter.swift
//  CleanSwift
//
//  Created by 이기완 on 2020/06/29.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BookListRoutingLogic {
    func routeToBookDetail(segue: UIStoryboardSegue?)
}

protocol BookListDataPassing {
    var dataStore: BookListDataStore? { get }
}

class BookListRouter: NSObject, BookListRoutingLogic, BookListDataPassing {
    weak var viewController: BookListViewController?
    var dataStore: BookListDataStore?
    
    // MARK: Routing
    
    func routeToBookDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! BookDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToBookDetail(source: dataStore!, destination: &destinationDS)
        }
        else {
            let storyboard = UIStoryboard(name: "BookListViewController", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "BookDetailViewController") as! BookDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToBookDetail(source: dataStore!, destination: &destinationDS)
            navigateToBookDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToBookDetail(source: BookListViewController, destination: BookDetailViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToBookDetail(source: BookListDataStore, destination: inout BookDetailDataStore) {
        if let indexPath = viewController?.tableView.indexPathForSelectedRow {
            destination.book = source.bookList!.list[indexPath.row]
            viewController?.tableView.deselectRow(at: indexPath, animated: true)
        }
        
    }
}
