//
//  BookListWorker.swift
//  CleanSwift
//
//  Created by 이기완 on 2020/06/29.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire



class BookListWorker {
    
    func requestBookList(completionHandler: @escaping (DataResponse<BookList.FetchBooks.Response, AFError>) -> Void) {
        AF.request("https://kxcoding-study.azurewebsites.net/api/books", method: .get)
            .responseDecodable(of: BookList.FetchBooks.Response.self) { (response: DataResponse<BookList.FetchBooks.Response, AFError>) in
                
                completionHandler(response)
        }
    }
}
