//
//  BookListPresenter.swift
//  CleanSwift
//
//  Created by 이기완 on 2020/06/29.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListPresentationLogic {
    func presentBookList(response: BookList.FetchBooks.Response)
}

class BookListPresenter: BookListPresentationLogic {
    weak var viewController: BookListDisplayLogic?
    
    // MARK: Do something
    
    func presentBookList(response: BookList.FetchBooks.Response) {
        
        var displayedBooks: [Book] = []
        
        for book in response.list {
            displayedBooks.append(book)
        }
        
        let viewModel = BookList.FetchBooks.ViewModel(displayedBooks: displayedBooks)
        viewController?.displayBookLists(viewModel: viewModel)
        
    }
}
