//
//  BookDetailModels.swift
//  CleanSwift
//
//  Created by kiwan on 2020/07/01.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BookDetail {
    // MARK: Use cases
    
    enum FetchBook {
        struct Request {
            let id: Int
        }
        
        struct Response: Codable {
            let code: Int
            let message: String?
            let book: Book
        }
        
        struct ViewModel {
            let book: Book
        }
    }
}
