//
//  BookDetailWorker.swift
//  CleanSwift
//
//  Created by kiwan on 2020/07/01.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class BookDetailWorker {
    
    func requestBookDetail(id: Int, completionHandler: @escaping (DataResponse<BookDetail.FetchBook.Response, AFError>) -> Void) {
        AF.request("https://kxcoding-study.azurewebsites.net/api/books/\(id)", method: .get)
            .responseDecodable(of: BookDetail.FetchBook.Response.self) { (response: DataResponse<BookDetail.FetchBook.Response, AFError>) in
                
                completionHandler(response)
        }
    }
}
