//
//  BookDetailPresenter.swift
//  CleanSwift
//
//  Created by kiwan on 2020/07/01.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailPresentationLogic {
    func presentBookDetail(response: BookDetail.FetchBook.Response)
}

class BookDetailPresenter: BookDetailPresentationLogic {
    weak var viewController: BookDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentBookDetail(response: BookDetail.FetchBook.Response) {
        let viewModel = BookDetail.FetchBook.ViewModel(book: response.book)
        viewController?.displayBookDetail(viewModel: viewModel)
    }
}
