//
//  BookListModels.swift
//  CleanSwift
//
//  Created by 이기완 on 2020/06/29.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

enum BookList {
    // MARK: Use cases
    
    enum FetchBooks {
        struct Request {            
            func bookList(completionHandler: @escaping (DataResponse<ViewModel.Books, AFError>) -> Void) {
                AF.request("https://kxcoding-study.azurewebsites.net/api/books", method: .get)
                    .responseDecodable(of: ViewModel.Books.self) { (response: DataResponse<ViewModel.Books, AFError>) in
                        completionHandler(response)
                }
            }
            
        }
        
        struct Response {
            let books: ViewModel.Books
        }
        
        struct ViewModel {
            struct Books: Codable {
                let totalCount: Int
                let code: Int
                let message: String?
                let list: [Book]
            }
            
            struct Book: Codable {
                let id: Int
                let title: String
                let description: String
                let yes24Link: String
                let publicationDate: String
            }
            
            let displayedBooks: [Book]
        }
    }
}
